### ISSUE TITLE
Redesign alert page layout.

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#441]
We need to redesign the layout of the alert page- for desktop mode only.

The layout should be as follows:
There are two columns. On the left one, there's the list of the alerts, including the map.
On the right side, there's the plan alert box, and below it, the tree alert box.

Something like that:
![image](https://user-images.githubusercontent.com/22238092/135593380-bf3bceb5-3a6d-43e6-84c2-4fed0183a253.png)

**Comment by Lishaysokol** [comment]
Thanks @winteromi. 
if we're keeping the current (whole page) layout, we definitely need to do something with the internal grid because the map and the list are both too narrow. I agree we the solution, wdyt about that way?

![image](https://user-images.githubusercontent.com/48589668/136711556-8a7a44fb-1bb9-432f-9607-ce67592eff14.png)

**Comment by drorgivton** [comment]
Addresses should be above the map, which is harder to read.

Also, changing the map component has also implications for the mobile
experience. I'd rather we have incremental improvements. So let's start
with a better layout, and open a new ticket for the next improvement.
