### ISSUE TITLE
Dispatch Digest email on Lambda

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#588]
Follow-up task for #583.

This task is about creating a process that consumes a message from an SQS queue- gets from it an id (referring to the file key at s3), reads property from the S3, and sends the appropriate parameters to the SendGrid service. 

The service should be completely independent of the meirim code base. It could be either within a new repo, or within an existing one, but it should not use any DB model, config or clients. 

Make sure to send the date param, referring to the send date, rather than the file creation date, because we want the email to reflect the sending date.

Also, please make sure we handle failures and delete the file after sending. 
* configuration- should be found within the lambda

**Comment by yaelal** [comment]
Longer message retention provides greater flexibility to allow for longer intervals between message production and consumption.

You can configure the Amazon SQS message retention period to a value from 1 minute to 14 days. The default is 4 days. Once the message retention quota is reached, your messages are automatically deleted.

**Comment by yaelal** [comment]
To configure the maximum message size, use the console or the SetQueueAttributes method to set the MaximumMessageSize attribute. This attribute specifies the number of bytes that an Amazon SQS message can contain. Set this attribute to a value between 1,024 bytes (1 KB), and 262,144 bytes (256 KB).

**Comment by yaelal** [comment]
A single Amazon SQS message queue can contain an unlimited number of messages. However, there is a quota of 120,000 for the number of inflight messages for a standard queue and 20,000 for a FIFO queue. Messages are inflight after they have been received from the queue by a consuming component, but have not yet been deleted from the queue.

**Comment by yaelal** [comment]
Amazon SQS API Reference. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/Welcome.html
AWS Lambda https://docs.aws.amazon.com/lambda/latest/dg/welcome.html

i still dont see a way that the lambda can do what you want
the cron thing is a limit

**Comment by yaelal** [comment]
but we can do something else
do the lambda trigger by queue but add a parameter to tell when to send the mail
so it isnt sent on weekend

https://docs.sendgrid.com/api-reference/mail-send/mail-send

send_at
integer
A unix timestamp allowing you to specify when you want your email to be delivered. This may be overridden by the send_at parameter set at the personalizations level. Delivery cannot be scheduled more than 72 hours in advance. If you have the flexibility, it's better to schedule mail for off-peak times. Most emails are scheduled and sent at the top of the hour or half hour. Scheduling email to avoid peak times — for example, scheduling at 10:53 — can result in lower deferral rates due to the reduced traffic during off-peak times.

**Comment by GalGend** [comment]
closed due to an aletranative solution
